### PR TITLE
Remove application/json from examples.

### PR DESCRIPTION
**Pull request by maciejmrowiec**
This resolves with missleasing request/response
examples on docs website.

Changelog: none

Signed-off-by: Maciej Mrowiec <mrowiec.maciej@gmail.com>

### CODE REVIEW

**Comment by maciejmrowiec** [comment]
@mendersoftware/rndity 

Looks like docs site have a bit miss-leading response/request examples that include application/json as part of the json object tree. https://docs.mender.io/1.4/apis/management-apis/device-admission#example-http-request

This is an attempt to check if we can remove those to get copy-past examples in docs website.

**Comment by maciejmrowiec** [comment]
yes, if we decide to keep it then I'll create something

**Comment by estenberg** [comment]
Thanks for fixing this!

**Comment by maciejmrowiec** [comment]
looks like it worked

**Comment by maciejmrowiec** [comment]
Followup task: https://tracker.mender.io/browse/MEN-1776

**Pull request merged**
